name: "AWS Route 53 Geolocation Updater"
description: "This GitHub Action updates the geolocation records of a domain in AWS Route 53 based on a list of countries."
branding:
  color: 'green'
  icon: 'check-square'

runs:
  using: node16
  main: index.js
